version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - "15672"    
    env_file:
      - ./config/.env.broker
  
  db:
    image: mysql
    container_name: main.mysql
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    
    env_file:
      - ./config/.env.db
     
    ports:
        - "7001:3306" 
    depends_on:
      - rabbitmq